name: MultiModalRest

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  # - nodejs  # for openneuro-cli
  - flake8
  - ipykernel
  # - nbconvert
  - dvc
  - dvc-s3
  - dvc-ssh
  - dvclive
  # - dvc-ssh
  - pytorch
  # - pytorch::pytorch-cuda  # comment out for CPU-only, use pinning to choose CUDA version
  - pytorch-lightning
  - torchmetrics
  - tensorboard
  - pandas
  - seaborn
  - xarray
  - h5netcdf
  - scikit-learn
  - nilearn
  # - pip:
  #     - antspyx
  #     - antspynet
  #   - torch-tb-profiler
