name: MultiModalRest

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # - nodejs  # for openneuro-cli
  - python
  - pip
  # - flake8
  - ipykernel
  # - jupyter_contrib_nbextensions
  # - nbconvert
  # - ipywidgets
  - dvc
  - dvc-s3
  - dvclive
  # - dvc-ssh
  - pytorch
  # - pytorch-cuda=11.7  # comment out for CPU-only
  - pytorch-lightning
  - torchmetrics
  - tensorboard
  - pandas
  - matplotlib
  - seaborn
  # - xarray
  # - h5netcdf
  - scikit-learn
  - nilearn
  # - pip:
  #   - torch-tb-profiler
